# This is a basic workflow to help you get started with Actions

name: Deploy to AWS EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-aws-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Decode and write SSH key
        run: echo "${{ secrets.EC2_PRIVATE_KEY }}" | base64 --decode > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa

      - name: Add SSH key to known hosts
        run: ssh-keyscan -H ${{ secrets.INSTANCE_IP }} >> $HOME/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ec2-user@${{ secrets.INSTANCE_IP }} 'cd /home/ssm-user/GIT-BASICS && git pull'
